### ISSUE TITLE
Project validation spam errors in the console when no main camera

### ISSUE THREAD

**Issue by anonymous2585** [microsoft/OpenXR-Unity-MixedReality-Samples#174] opened 2024-03-05 14:01 UTC
Hi,

I just updated to Unity 2023.2.12f1, so OpenXR updated automatically to 1.10.0.
I manually updated the microsoft OpenXR plugin to 1.10.0.

In our application, there is a root scene that load sub-root scene depending on the plateform.
The main camera is in the sub-root scene, so most of the time, I don't have a main camera open in the editor.

When opening the OpenXR Project Validation, it spam this error, because there is no main camera:
```
NullReferenceException: Object reference not set to an instance of an object
Microsoft.MixedReality.OpenXR.Editor.PlatformValidation+<>c.<GenerateCameraFlagsRule>b__35_1 () (at ./Library/PackageCache/com.microsoft.mixedreality.openxr@6b31efb96f12/Editor/Settings/PlatformValidation.cs:465)
Unity.XR.CoreUtils.Editor.BuildValidator.GetCurrentValidationIssues (System.Collections.Generic.HashSet`1[T] failures, UnityEditor.BuildTargetGroup buildTargetGroup) (at ./Library/PackageCache/com.unity.xr.core-utils@2.3.0/Editor/ProjectValidation/BuildValidator.cs:94)
Unity.XR.CoreUtils.Editor.ProjectValidationDrawer.UpdateIssues (System.Boolean focused, System.Boolean force) (at ./Library/PackageCache/com.unity.xr.core-utils@2.3.0/Editor/ProjectValidation/ProjectValidationDrawer.cs:475)
Unity.XR.CoreUtils.Editor.ProjectValidationSettingsProvider.OnInspectorUpdate () (at ./Library/PackageCache/com.unity.xr.core-utils@2.3.0/Editor/ProjectValidation/ProjectValidationSettingsProvider.cs:45)
UnityEditor.SettingsWindow.OnInspectorUpdate () (at <3e46df4d8aed4ee0a868f68610838aae>:0)
UnityEditor.HostView.OnInspectorUpdate () (at <3e46df4d8aed4ee0a868f68610838aae>:0)
```

**Comment by AMollis** [comment] 2024-03-11 16:24
@marlenaklein-msft can you please investigate

**Comment by marlenaklein-msft** [comment] 2024-04-18 19:02
@anonymous2585, @AMollis. Thanks for reporting this! The issue is fixed in the1.10.1 patch release

**Closed by marlenaklein-msft** 2024-04-18 19:02 UTC
