### ISSUE TITLE
Error "The type or namespace name 'SceneSystem' does not exist in the namespace 'CoreServices'" at BasicSample project startup

### ISSUE THREAD

**Issue by fcsp1** [microsoft/OpenXR-Unity-MixedReality-Samples#21] opened 2021-06-03 11:00 UTC
Hello,
I downloaded the repository and opened the BasicSample project with Unity 2020.3.11f1 and these three errors showed up:

![mrtk-scenesystem](https://user-images.githubusercontent.com/47389374/120633722-5e211e80-c462-11eb-9b3b-beb87e01612a.png)

I fixed the issue by adding `Toolkit` before the `CoreServices` namespace to each of the three lines of code with the error (i.e. in the SceneLoader script I modified the line 
`public void LoadScene(string sceneName) => CoreServices.SceneSystem.LoadContent(sceneName, LoadSceneMode.Single);`
into 
`public void LoadScene(string sceneName) => Toolkit.CoreServices.SceneSystem.LoadContent(sceneName, LoadSceneMode.Single);`, the same for the other two scripts).

After the project recompiled the code, everything worked fine!

**Comment by keveleigh** [comment] 2021-06-03 16:11
Thanks for the report! Unfortunately, this is caused by Unity's inadvertent inclusion of some types in a `CoreServices` namespace in the Version Control UPM package. If you're not using this package (I think it's included by default), you can uninstall it from the Unity Package Manager. Last I heard, Unity was planning a fix.

This package will also be removed from this repo after #20 is merged.

**Closed** 2021-06-03 16:32 UTC
