### ISSUE TITLE
Gap of the pinch gesture

### ISSUE THREAD

**Issue by olcsa** [microsoft/OpenXR-Unity-MixedReality-Samples#167] opened 2023-09-14 16:34 UTC
Lately we recieved user feedbacks that they accidently grab objects with the pinch gesture. We've investigated this issue and it turned out that we can grab the virtual content with wider gap between the index finger and the thumb. If i grab a window/3d icon in the HoloLens' main menu the gap is smaller (half compared to the app).

It seems that it is related to the Mixed Reality OpenXR plugin, the only change to the project we made was downgrading the plugin to 1.7.2, and it solved this pinch gesture issue.

To reproduce:
- Open a Unity 2020 LTS or 2021 LTS project
- Import MRTK 2.8.3 with MR OpenXR plugin 1.8.0 or above
- Create MR scene for HoloLens 2
- Add 3d object with MRTK's ObjectManipulator on it
- Remote to the editor
- Grab the object with the pinch gesture in far interection mode

**Comment by AMollis** [comment] 2023-10-27 19:45
@marlenaklein-msft , can you investigate this?

@olcsa , does the same issue occur in the MR Plugin 1.9?

**Comment by olcsa** [comment] 2023-11-03 13:08
@AMollis, Yes, I've tested with the 1.9 and 1.8 too, the issue still occured.

**Comment by bende01** [comment] 2024-01-12 14:05
Hi, is there any update with this issue? I tested it with 1.10 and the problem is the same.

**Comment by iantrobinson** [comment] 2024-01-12 17:20
Same here. It is very frustrating when a fairly neutral hand position
suddenly grabs an object.

**Comment by marlenaklein-msft** [comment] 2024-03-15 00:10
Hi, thanks for reporting this issue. Just to confirm, this only occurs when using holographic remoting? Or also when building to device?

**Comment by Guillaume-Git** [comment] 2024-03-15 09:13
Thanks for your answer. Yes I confirm that it only occurs when using holographic remoting. When I build to device, the pinch gesture works just fine.

**Comment by marlenaklein-msft** [comment] 2024-03-19 17:06
I was able to repro the issue. As a test, confirmed that using the MR Plugin 1.8.0 and manually changing the HAR dlls from 2.9.1 to 2.8.1, the pinch gap behaves as normal. 

@lappelsmeier, @AMollis it seems this is a change in behavior from HAR 2.8.1 to 2.9.1

**Comment by Guillaume-Git** [comment] 2024-03-20 14:34
@marlenaklein-msft I would like to use the 1.10.0 version and change the HAR dlls manually to fix the pinch gap temporarily before a new version is released to fix the issue. Do you think it is possible? Where are the dlls located?

**Comment by marlenaklein-msft** [comment] 2024-03-20 18:02
@Guillaume-Git I tested this by changing the dlls in the PackageCache (Library > PackageCache > com.microsoft.mixedreality.openxr > Runtime > windows > x64). I replaced the 2.9.1 HAR dlls in my 1.8.0 project with the 2.8.1 ones from my 1.7.2 project.

I'm not sure whether there are any differences in 1.10 that would prevent it from working there. This isn't an expected/supported method, just a test to narrow down the problem, so the plugin hasn't been officially validated with that version of HAR.

**Comment by Guillaume-Git** [comment] 2024-03-21 08:41
Thank you! I will try this workaround for now and keep you updated.

**Comment by bende01** [comment] 2024-04-02 12:57
@Guillaume-Git Did you manage to use the workaround?

**Comment by Guillaume-Git** [comment] 2024-04-02 13:02
Sorry, I haven't been able to test it yet as I'm busy with something else for the moment.

**Comment by AMollis** [comment] 2024-08-16 04:13
@olcsa  this issue has been fixed in the remoting runtime v2.9.4, which is included in OpenXR MR Plugin v1.11.1

More information here:

https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/releases/tag/v1.11.1

**Closed by AMollis** 2024-08-16 04:13 UTC
