### ISSUE TITLE
Azure Spatial Anchors not consistently located in sample

### ISSUE THREAD

**Issue by robbbbbb** [microsoft/OpenXR-Unity-MixedReality-Samples#51] opened 2021-10-14 14:21 UTC
## The bug

In the [ASA Sample](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/tree/main/AzureSpatialAnchorsSample) anchors that were previously created locally (or indeed any valid ASA anchor) are only found about 30% of the time. 

The first time the device attempts to find an anchor it has just saved, it almost always succeeds.

On subsequent attempts (i.e. the watcher has been deleted, the session stopped, and a new session started) it almost always fails to find the anchor. This seems to be unrelated to lighting conditions, consistency of the environment, position + orientation of the headset, or anything else. When location fails, no errors are ever logged by the SDK internals, and AnchorLocated is never called with any arguments.

## To reproduce

1. Build and run the ASA Sample
2. Tap 'Start Session'
3. Place 2 anchors by air tapping
4. Save both anchors by air tapping in their boxes
5. Confirm both have been saved
6. Tap 'Stop Session' 
7. Tap 'Start Session' 
8. Observe that both anchors were located and appear as green boxes
9. Tap 'Stop Session'
10. Tap 'Start Session'
11. Observe that (usually) at least one, or both of the anchors are never located
12. Repeat steps 9-11 several times (varying the wait between stopping and restarting the session if you want to), and observe that the ability of the SDK to locate the anchors is seemingly random (and usually fails).

## Expected behavior

Under reasonable environmental conditions an ASA anchor in a given location should always be found, or at least some error logging should happen against the SpatialAnchorManager's Error callback.

## Setup

Unity Version: 2020.3.19f1
MRTK Version: 2.7.2
Unity OpenXR Plugin Version: 1.2.8
Mixed Reality OpenXR Plugin Version: 1.0.3.0
Windows Mixed Reality Runtime: 107.2109.10010
Device OS Version: 10.0.20348.1018
Azure Spatial Anchors SDK Version: 2.10.0-beta0014

**Comment by KBonds** [comment] 2021-11-16 01:50
@robbbbbb the ASA sample project has recently been updated to use version 2.10.2 of the ASA SDK.

From what I can repro, the issue you described is no longer occurring. With this latest SDK package, I have occasionally observed issues with ASA anchors not locating properly, but not in a manner where "when location fails, no errors are ever logged by the SDK internals, and AnchorLocated is never called with any arguments." 

I'm curious if this issue you've reported seems solved on your end as well and if the logging when errors occur is now sufficient for you.

**Comment by robbbbbb** [comment] 2021-11-17 12:31
@KBonds you can see more info in [this linked issue](https://github.com/Azure/azure-spatial-anchors-samples/issues/312), but at a high level I can tell you that it really depends on the OS version and the OpenXR runtime version the particular device you're using is on. Several of your Microsoft colleagues, including @yl-msft and @msftradford are investigating this and related issues with the OS and OpenXR runtimes.

If you want to help narrow this down it'd be useful if you could re-run your tests (with 2.10.2) but note down all of these aspects of your environment when you do (you can see the version number formats I used in my original post if it helps):

Unity Version
MRTK Version
Unity OpenXR Plugin Version
Mixed Reality OpenXR Plugin Version
Windows Mixed Reality Runtime
Device OS Version
Azure Spatial Anchors SDK Version

**Comment by KBonds** [comment] 2021-12-09 01:50
@robbbbbb the ASA sample has once again been updated, to version 2.11.0 now. This version of the ASA package seems to work correctly for me, even resolving the issues we mentioned in the previous 2.10.2 release.

I appreciate the link to the azure-spatial-anchors-samples issue related to this - I expect that thread can be used to track any future progress on the various ASA issues that thread mentions.

Since the issue reported here seems resolved and other issues are being tracked on the other repo, I'm looking towards closing this issue here. I wanted to give you the opportunity to first try this new version out, if you'd like.

**Comment by robbbbbb** [comment] 2021-12-09 11:01
Hi @KBonds I haven't been able to repro these issues on device since the 20348.1438 OS update in October, so I'm doubtful the change from 2.10.2 > 2.11.0 is really responsible for anything being fixed. But thanks for the update anyway.

**Comment by yl-msft** [comment] 2021-12-09 18:02
@robbbbbb , Glad that the scenario is working for you.   To my understanding ASA team and you have not confirmed about the issue you were seeing are related to OS updates either.  Yet, may I confirm with you that with the latest OS on HL2, latest Unity engine and openxr/ASA plugin, the scenarios works for you?  If so, we'd like to close this issue so we can shift resource to solve other bugs for customers.   Thanks a lot for your engagement with us. @robbbbbb

**Closed** 2022-01-04 00:44 UTC
