### ISSUE TITLE
Image stabilization problems after resuming the app

### ISSUE THREAD

**Issue by WikkidEdd** [microsoft/OpenXR-Unity-MixedReality-Samples#52] opened 2021-10-22 10:45 UTC
**Note: This issue has been moved from this other repo for better visibility https://github.com/WikkidEdd/OpenXRTestProject/issues/3**

## Describe the bug

If you use the start menu to put the app into the background and then tap the app slate to resume it results in the stabilization being disabled.

## To reproduce

1. Clone this git repo
2. Open Basic Sample Unity project
3. Switch to UWP build platform
4. Build the application.
5. Switch solution config to Release and ARM64
6. Build and Start the application
7. Observe that the content in the scene is stable when moving your head
8. Bring up the start menu and press the home button
9. Resume the app by pressing the app slate in the world (or from the start menu if the app slate doesn't exist yet).
10.  Observe that the content is now unstable when moving your head

It's probably also worth noting that in this sample project when the issue occurs the whole image is unstable consistently, but in our actual app, we get slightly different behavior. It's like parts of the depth buffer is incomplete, so some parts are stable and some parts are jittering. 

## Expected behavior

The application should resume with the same quality stabilization as before backgrounding the app

## Your setup (please complete the following information)

- Unity Version 2020.3.19
- Unity OpenXR Package 1.2.8
- Mixed Reality OpenXR Package 1.0.3 and 1.1.1 tested
- Holographic OS 20348.1018
- OpenXR Runtime Version 107.2109.10010.0

## Target platform (please complete the following information)
- HoloLens 2

**Comment by mihaits** [comment] 2021-11-08 13:44
can confirm this has always happened to me with OpenXR. Reproducible with everything updated as of 2021-11-08:
Unity 2021.1.28f1
MRTK 2.7.3
Mixed Reality OpenXR plugin 1.1.2
![giphy](https://user-images.githubusercontent.com/27222926/140752634-612546ce-4b64-483a-9031-06a49b7e4aee.gif)

**Comment by JPhilC** [comment] 2021-11-08 14:12
I too have recently upgraded an app to Unity 2020.3.19f1 and OpenXR. My customer is now complaining that the app is:

"jumping around a lot (unstable)"

and also,

"I have noticed that if you turn off the device without closing the app when you open the device again and try opening the app it doesn't work."

By turning off they mean pressing the device power button.

**Comment by yl-msft** [comment] 2021-11-10 05:54
Update on this issue, the team is still working together with Unity team on this scenario of turning HL2 off and then turning on to resume an openxr unity app.  We are peeling the onion here and getting the scenario better.  We will keep this thread updated when we roll out some of our fixes.  we have not yet land the last fixes yet.

**Comment by yl-msft** [comment] 2022-02-18 02:23
@WikkidEdd @JPhilC, @mihaits , @AMollis, 
OpenXR team recently released 110 preview runtime that fixed this issue.  Please try it out and let us know your experience.

Please reference to this link for instructions: https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/issues/53#issuecomment-1043747065

**Comment by mihaits** [comment] 2022-02-28 15:21
spent some time testing
OpenXR runtime 109:
**Bug**: when resuming the app it results in broken stabilization on mostly the lower part of the screens like I posted [here](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/issues/52#issuecomment-963163554). exiting and trying to resume again right after results in indefinitely spinning white balls. In rare cases I get the spinning balls first time. seems #53 related
- I can't reproduce by just exiting and resuming the app right after. might have happened once in a few dozen resumes but not sure
- I can sometimes reproduce it when resuming if the device was put to sleep (by power button or timeout) after starting the app.
OpenXR runtime 110 preview:
- couldn't reproduce!

**Comment by yl-msft** [comment] 2022-03-08 06:15
@mihaits   thanks for trying this out.  Sounds the runtime 110 preview fixed the issue you were reporting.  We are also looking forward for this 110 runtime to officially released in a few weeks.

**Comment by yl-msft** [comment] 2022-06-07 03:57
The 110 openxr runtime on HoloLens 2 has been released to 100% to all users.  Make sure you've received it in from Store updates.

**Closed by yl-msft** 2022-06-07 03:57 UTC
