### ISSUE TITLE
No GetDeviceLayoutName() override detected

### ISSUE THREAD

**Issue by lukefanning** [microsoft/OpenXR-Unity-MixedReality-Samples#178] opened 2024-03-24 14:55 UTC
​
Hi, sorry not sure if this is the best place to create this issue, since Unity OpenXR Plugin v1.9.1 (2023-10-19), they added a couple of new API functions for controller profiles (OpenXRInteractionFeature) the first of which, `GetDeviceLayoutName()` if not overridden results in a warning when loading up a project and when running it in Play mode/Standalone.

i.e.

No GetDeviceLayoutName() override detected in HP Reverb G2 Controller Profile. Binding path validator for this interaction profile is not as effective. To fix, add GetDeviceLayoutName and GetInteractionProfileType override in this profile.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

​

**Comment by AMollis** [comment] 2024-03-26 16:24
@marlenaklein-msft   can you please investigate resolving this warning in the sample?  We might want to also update the sample to the latest Unity OpenXR Plugin 

(Marlena I've created an internal bug tracking this issue as well)

**Comment by Ron-66** [comment] 2024-05-18 07:40
Here's how to temporarily suppress the warning until the package is updated. The cause is that the `GetDeviceLayoutName` method is not overridden in `Runtime\FeaturePlugins\HPMixedRealityControllerProfile.cs`. Therefore, please add the following `GetDeviceLayoutName` method between the `UnregisterDeviceLayout` method and the `RegisterActionMapsWithRuntime` method around line 276 in `HPMixedRealityControllerProfile.cs`:

```cs
/// <summary>
/// Return device layout string that used for registering device for Input System.
/// </summary>
/// <returns>Device layout string.</returns>
protected override string GetDeviceLayoutName()
{
    return nameof(HPMixedRealityController); }
}
```

**Comment by Schroedingers-Cat** [comment] 2024-09-12 07:21
With the OpenXR plugin version 1.11.1, you'll also have to override `GetInteractionProfileType()` at line 276 than with previous versions:
```csharp
        /// <summary>
        /// Return device layout string that used for registering device for Input System.
        /// </summary>
        /// <returns>Device layout string.</returns>
        protected override string GetDeviceLayoutName() {
            return nameof(HPMixedRealityController);
        }

        /// <inheritdoc/>
        protected override InteractionProfileType GetInteractionProfileType() {
            return base.GetInteractionProfileType();
        }
```

Is there any chance for this to be picked up upstream? There has been an OpenXR plugin release a month after the fix has been posted. I tried to find the OpenXR plugin's repository to make the developers aware of this. Unfortunately, I had no luck finding it.

**Comment by marlenaklein-msft** [comment] 2024-11-15 04:03
Thank you for logging this and the fix! This will be included in the HPMixedRealityControllerProfile in the next release.

**Comment by marlenaklein-msft** [comment] 2024-12-05 19:31
This change has been made in the 1.11.2 release! Please reopen this thread if there continue to be any issues.

**Closed by marlenaklein-msft** 2024-12-05 19:31 UTC
